import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { build } from 'esbuild';

const here = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(here, '..');

export const AGENT_ENTRY = path.join(ROOT, 'src/recorder/agent/main.ts');
export const AGENT_BUNDLE_FILE = path.join(ROOT, 'src/recorder/agent-bundle.generated.ts');

/**
 * Compile the in-page agent to a single self-contained IIFE.
 *
 * `keepNames` is off deliberately. With it on, esbuild rewrites every function
 * declaration to `__name(fn, "…")`, and those helpers do not exist in page
 * scope — which is exactly how the agent once threw on its first line and
 * recorded nothing at all, silently, while the test suite stayed green.
 *
 * Bundling replaces `Function.prototype.toString()` serialization entirely, so
 * whatever toolchain compiles the host can no longer affect what runs in the page.
 */
export async function buildAgentBundle(): Promise<string> {
  const result = await build({
    entryPoints: [AGENT_ENTRY],
    bundle: true,
    format: 'iife',
    platform: 'browser',
    target: 'es2020',
    keepNames: false,
    minify: false,
    write: false,
    legalComments: 'none',
  });

  const output = result.outputFiles?.[0];
  if (!output) throw new Error('esbuild produced no output for the agent bundle.');

  const code = output.text;
  // Cheap belt-and-braces: any surviving build helper would be a page-scope
  // ReferenceError, and the failure mode is silent.
  const leaked = ['__name(', '__publicField(', '__toESM(', '__commonJS('].filter((h) =>
    code.includes(h),
  );
  if (leaked.length) {
    throw new Error(
      `Agent bundle references build helpers that do not exist in the page: ${leaked.join(', ')}`,
    );
  }
  return code;
}

/** Render the generated module. Compared verbatim by the freshness test. */
export function renderModule(code: string): string {
  return `// GENERATED by scripts/build-agent.ts — do not edit.
// Source: src/recorder/agent/main.ts. Regenerate with \`npm run build:agent\`.
/* eslint-disable */

/** The in-page capture agent, bundled as a standalone IIFE. */
export const AGENT_BUNDLE = ${JSON.stringify(code)};
`;
}

export async function writeAgentBundle(): Promise<boolean> {
  const next = renderModule(await buildAgentBundle());
  const current = await readFile(AGENT_BUNDLE_FILE, 'utf8').catch(() => null);
  if (current === next) return false;
  await writeFile(AGENT_BUNDLE_FILE, next, 'utf8');
  return true;
}

// Run directly (npm run build:agent) rather than when imported by a test.
if (process.argv[1] && path.resolve(process.argv[1]) === path.resolve(fileURLToPath(import.meta.url))) {
  const changed = await writeAgentBundle();
  const size = (await readFile(AGENT_BUNDLE_FILE, 'utf8')).length;
  console.log(`agent bundle ${changed ? 'updated' : 'unchanged'} (${(size / 1024).toFixed(1)} kB)`);
}
